namespace: devops
name: devops_virtualization_collection
version: 1.0.0
readme: README.md
authors:
  - "Laszlo Beres laszlo.beres1990@gmail.com"
description: "Configuration Proxmox node"
license_file: "LICENSE"
license:
  - "GPL-2.0-or-later"
tags:
  - virtualization
  - proxmox
dependencies: {}
repository: https://github.com/eresseel/devops_virtualization_collection
documentation: https://github.com/eresseel/devops_virtualization_collection/README.md
homepage: https://www.eresseel.org
