FROM debian:12
ENV DEBIAN_FRONTEND noninteractive

# set mirror
RUN rm /etc/apt/sources.list.d/debian.sources && \
    echo "deb http://deb.debian.org/debian/ bookworm main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian/ bookworm-backports main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian-security bookworm-security main contrib" >> /etc/apt/sources.list

# install base pkg
RUN apt-get update && \
    apt-get install -y wget systemctl curl gnupg ca-certificates python3-minimal python3-apt

#add proxmox repo
# RUN echo "deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise" >>/etc/apt/sources.list
# echo "deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise" >> /etc/apt/sources.list.d/ceph.list && \
RUN echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" >> /etc/apt/sources.list.d/pve-no-subscription.list && \
    curl https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg | apt-key add -

# http://download.proxmox.com/debian/pve/dists/bookworm/pve-no-subscription/binary-amd64/
# repacked proxmox-ve
RUN wget http://download.proxmox.com/debian/pve/dists/bookworm/pve-no-subscription/binary-amd64/proxmox-ve_8.1.0_all.deb && \
    mkdir /tmp/pve && \
    dpkg -X proxmox-ve_8.1.0_all.deb /tmp/pve/ && \
    dpkg -e proxmox-ve_8.1.0_all.deb /tmp/pve/DEBIAN && \
    sed -i "s/proxmox-kernel-helper (>= 8.0.3),//g" /tmp/pve/DEBIAN/control && \
    sed -i "s/proxmox-default-kernel,//g" /tmp/pve/DEBIAN/control && \
    dpkg-deb -Zxz  -b /tmp/pve/ /tmp/

# repacked pve-manager
RUN wget http://download.proxmox.com/debian/pve/dists/bookworm/pve-no-subscription/binary-amd64/pve-manager_8.1.4_amd64.deb && \
    mkdir /tmp/pve-manager && \
    dpkg -X pve-manager_8.1.4_amd64.deb  /tmp/pve-manager/ && \
    dpkg -e pve-manager_8.1.4_amd64.deb /tmp/pve-manager/DEBIAN && \
    sed -i "s/ifupdown2 (>= 3.0) | ifenslave (>= 2.6),//g" /tmp/pve-manager/DEBIAN/control && \
    dpkg-deb -Zxz  -b /tmp/pve-manager/ /tmp

# intall proxmox-ve without recommends. ifupdown2 will install failed but ok
RUN apt-get update && \
    apt-get -y --no-install-recommends install proxmox-ve || echo ok

# install again
RUN dpkg -i /tmp/*.deb || echo ok && \
    chmod 1777 /run /run/lock

# set passwd for root
RUN echo "root:root" | chpasswd

# clean
RUN apt-get autoremove -y || echo ok && \
    rm -rf /var/lib/apt/lists/*  /*.deb

# use setup.sh to start proxmox service
STOPSIGNAL SIGINT
CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target"]

# docker run -itd -v /sys/fs/cgroup/system.slice/:/sys/fs/cgroup:rw --cgroupns=host --network host --device=/dev/kvm --device /dev/fuse --tmpfs /run:rw --tmpfs /run/lock:rw --tmpfs /tmp:rw --name pve --add-host pve:192.168.59.100 --hostname pve proxmox:latest
